name: GitHub Actions - Trigger
run-name: Running - ${{ github.event_name }}
on: 
  workflow_run:
    workflows: [GitHub Actions - Trigger]
    # types: [completed]
    # branches: [main]
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Workflow que foi trigado"
