name: GitHub Actions - Configuração de Variavel de Ambiente
run-name: Running - ENV Var Repo Config
on: [push, workflow_dispatch]
env:
  variavel: "Bom dia"
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "$variavel"