name: GitHub Actions - Configuração de Variavel de Ambiente
run-name: Running - ENV Var Repo Config
on: [push, workflow_dispatch]
env:
  variavel: "Bom dia"
  var_2: ${{ vars.test_var }}
  var_3: ${{ secrets.test_secret }}
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "$variavel"
          echo "$var_2"
          echo "$var_3"