name: GitHub Actions - Gerenciamento de erros
run-name: Running - Gerenciamento de erros
on: [push, workflow_dispatch]

jobs:
  job_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo Comentário antes do erro
          exit 1
          
      - name: Comentário
        if: always()
        run: |
          echo Comentário após o erro
  
  
  on_workflow_dispatch_only:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo ${{ github.event_name }}